### ISSUE TITLE
Remove node_modules from git

### ISSUE THREAD

**Issue by josemvidal** [SCCapstone/StyleMail#108]
The [StyleMail/stylemail/test/node\_modules](https://github.com/SCCapstone/StyleMail/tree/master/stylemail/test/node_modules) folder never goes in git. Remove it.

**Comment by gwerven** [comment]
Our team has removed the node_modules folder from the test directory. Thank you for making us aware of best practices! As a result, our project size has been reduced significantly. Would you prefer that we make a new git tag?

**Comment by josemvidal** [comment]
Nope. No need for a new tag.
