### ISSUE TITLE
Assign one person to each Beta Issue

### ISSUE THREAD

**Issue by josemvidal** [SCCapstone/StyleMail#110]
Looks you started assigning people to Issues, but so far only 1 person is assigned something to do. Remember, if no one is assigned to an Issue, no one will do it!

Assign each Issue to one person.

![image](https://user-images.githubusercontent.com/228704/106799954-dd762100-662d-11eb-9efc-3dfe0daf6506.png)

**Comment by gwerven** [comment]
Each beta issue has now been assigned to one team member.
