### ISSUE TITLE
Progress Report

### ISSUE THREAD

**Issue by josemvidal** [SCCapstone/StyleMail#112]
Everyone in the team write a short comment on what you have been working on so far: progress? any problems or issues?

If you are the last person in the team to comment then Close this Issue when you are done.

Try to get this done by  **February 14** or so.

**Comment by gwerven** [comment]
-Ran trial run of the team's unit and behavioral tests and updated the testing section of the readme.
-Began working on implementing functionality for the user to customize templates using a React form as well as sending emails from the web app using a node library. Working with the team to implement these features into the existing user interface.
-Started a Trello board for team management

**Comment by oliviaamontyy** [comment]
Attend the weekly team meetings.
Working on Navigation bar for the Beta Release -- currently switches depending on being logged in or not, but still working on getting the Navigation bar correct when you go to the already deployed Web Application.
Began working and researching how to create the Wedding and Valentines day templates for the Beta Release

**Comment by alecfarmer** [comment]
Continued work on the firestore database so the user to save, modify, and delete email templates while keeping edited templates connected to the correct user. Also began work on the Good Luck and Christmas Party Invite email templates for the next release.

**Comment by sistewart** [comment]
Attended the group meeting this past week. Fixing the navigation bar on the html page to match the one in react. Creating the Graduation Announcement, Baby Announcement, and Thank You cards for the Beta Release. I had a lot of issues the past couple of weeks with my NPM modules being out of date - and this never happened last semester.

**Comment by khegs99** [comment]
I am working to finalize firebase storage of the templates and push that code. Along with that, I am working on templates for get well cards and business meetings. I have not run into any big issues other than trying to get to the code to run on everyone’s machine.

**Comment by josemvidal** [comment]
Looks good! Keep pushing those [commits](https://github.com/SCCapstone/StyleMail/network)!

Let me know if you have any questions or problems.
