### ISSUE TITLE
Templates created or deleted in the previous login are not saved

### ISSUE THREAD

**Issue by iqbal128855** [SCCapstone/StyleMail#59]
![style-mail-2](https://user-images.githubusercontent.com/12802456/101377519-ecd02c80-387f-11eb-97fe-caccc8e98d79.gif)

**Comment by josemvidal** [comment]
Confirmed.

**Comment by josemvidal** [comment]
If the user Reloads the page the number of templates is re-set. Thus, they are not being saved to the backend.
