### ISSUE TITLE
Add Beta Issues

### ISSUE THREAD

**Issue by josemvidal** [SCCapstone/StyleMail#61]
Please add all the features you will implement for the [Beta Milestone](https://capstone.cse.sc.edu/milestone/beta/) as Issues, with label:enhancement, and associate them with the Beta Milestone.

When you are done adding your Beta Issues, close this Issue. I will then take a look at them and might comment on them, ask you add more, etc. In the end I will approve the issues and paste their numbers right in here.

Please add your Beta Issues by **January 25**.

**Comment by josemvidal** [comment]
The core functionality of this app is the creating, customizing, and sending of pretty emails.

Do the Beta Issues implement this functionality? Answer below. It seems they do, but I don't remember what has been already implemented.

**Comment by gwerven** [comment]
Yes, that is the core functionality of the app. The beta issues implement all of those functionalities. User accounts and basic template management had been implemented in the v0.1 release.

**Comment by josemvidal** [comment]
Looks good. Beta features approved: #100 #101 #102 #103 #104 #105 #106 #63 #64 #65 #66 #67 #68 #69 #70 #71 #72 #73 #74 #75 #76 #77 #78 #79 #80 #81 #82 #83 #84 #85 👍
